import './globals.css'
import type { Metadata } from 'next'
import Head from 'next/head';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Head>
      <title>Cool Title</title>
      <meta property="og:title" content="Gender Reveal" />
      <meta
        property="og:description"
        content="Gender Reveal Invitation for our party"
      />
      <meta
        property="og:image"
        content="https://example.com/images/cool-page.jpg"
      />
    </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
